using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using QuanLyKho.Data;
using QuanLyKho.Middleware;
using QuanLyKho.Services;
using QuestPDF.Infrastructure;
var builder=WebApplication.CreateBuilder(args);
QuestPDF.Settings.License=LicenseType.Community;
var cs=builder.Configuration.GetConnectionString("QuanLyKhoDb")??throw new InvalidOperationException("Connection string 'QuanLyKhoDb' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(o=>o.UseSqlServer(cs));
var key=builder.Configuration["Jwt:Key"]??throw new InvalidOperationException("JWT key is not configured.");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new TokenValidationParameters{ValidateIssuer=true,ValidateAudience=true,ValidateLifetime=true,ValidateIssuerSigningKey=true,ValidIssuer=builder.Configuration["Jwt:Issuer"],ValidAudience=builder.Configuration["Jwt:Audience"],IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),ClockSkew=TimeSpan.FromSeconds(30)});
builder.Services.AddAuthorization();builder.Services.AddControllers();
builder.Services.AddCors(o=>o.AddPolicy("ReactClient",p=>p.WithOrigins("http://localhost:5173","https://localhost:5173").AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddScoped<AuthService>();builder.Services.AddScoped<CategoryService>();builder.Services.AddScoped<ProductService>();builder.Services.AddScoped<ReceiptService>();builder.Services.AddScoped<IssueService>();builder.Services.AddScoped<InvoiceService>();builder.Services.AddScoped<ReportService>();builder.Services.AddScoped<UserService>();builder.Services.AddScoped<DashboardService>();
var app=builder.Build();app.UseMiddleware<ExceptionHandlingMiddleware>();app.UseHttpsRedirection();app.UseCors("ReactClient");app.UseAuthentication();app.UseAuthorization();app.MapControllers();
using(var scope=app.Services.CreateScope())DbInitializer.Initialize(scope.ServiceProvider.GetRequiredService<ApplicationDbContext>());
app.Run();